### ISSUE TITLE
Program Crashes after game is attached

### ISSUE THREAD

**Issue by Adderlen** [tremwil/SteamP2PInfo#11]
Hello there ! Downloaded and did everything as told in the description. But after I attached the game, the program crashes overlay closes. I tried not to press anything in the crash window to test the overlay but no use because the overlay is on but shows nothing =(
Screenshot of the crash message attached. Hope you can help :( ty 

![zyhMyP6h9p](https://user-images.githubusercontent.com/104527661/165604638-27413f2b-4450-4741-95f7-685d09016ae7.png)

**Comment by tremwil** [comment]
Hi! Could you please translate the human-readable error message on the first line? Without it I cannot be sure this is the issue, but it most likely has to do with the Steam IPC log file not existing at the expected path. If this is the issue, changing the "Steam IPC log file path" setting in the settings tab to match your local Steam installation should fix it.

**Comment by tremwil** [comment]
Hi! Could you please translate the human-readable error message on the first line? Without it I cannot be sure this is the issue, but it most likely has to do with the "config" folder being absent, preventing the program from working properly. Are you certain your installation directory contains all the required files and folders which were provided in the zip file?

**Comment by Adderlen** [comment]
Yes sure, it is "Access to the following direction is denied"
and yep, all files from zip are here
![n29541UBTZ](https://user-images.githubusercontent.com/104527661/165647110-1605f536-51fc-40fe-beb4-d7a632bd805f.png)

**Comment by Adderlen** [comment]
Hey Its me again, I figured out what was the problem. It is my fault, in "config" was the default way to SteamClient.log file, but I installed steam on disc D: so I changed it and It works now perfectly :3  sorry for inconvenience  and ty for the program

**Comment by tremwil** [comment]
Thanks for the report anyways! This definitely shouldn't crash the program, it's supposed to simply tell you the log file could not be found. I'll fix it to cover more potential file errors.
