### ISSUE TITLE
Recent Players List?

### ISSUE THREAD

**Issue by j-6-w3n7w027h** [tremwil/SteamP2PInfo#12]
I've heard from multiple sources that Elden Ring on Steam has a functional recent players list. In my attempt to figure this feature out, I've found this excellent little program. It works great for me, just a couple questions though. In the readme, it says you can use the program to log recent players to the recent players list; I cant find this functionality. How do I do this? Also, is it possible for the names of the recent players to be logged to the log file? In other words, after I disconnect from a player, is there a way for me to go back and see who I had connected with? Sorry if this isn't really an "issue," I just would like some clarification and potentially help future users of this program. Thanks for the hard work.

**Comment by Jiur13** [comment]
you can check recent players via steam directly, press view on top left of steam, then players, then a box will appear showing you who you recently played with in ER

**Comment by j-6-w3n7w027h** [comment]
BRO THANK YOU. I thought it just wasn't working for me, I've been trying:
> *steam name* > friends > recently played with
Good job clearing up my idiocy, right on.
