### ISSUE TITLE
no player info appearing on overlay or the program itself

### ISSUE THREAD

**Issue by daylight1943** [tremwil/SteamP2PInfo#20]
player info does not appear whatsoever in the overlay or in the steam p2p window itself. this is not an occasional thing, i have never once seen anything besides "Steam p2p info by tremwil" on the overlay and have never seen any info displayed in the main program window, it is always 100% blank. how can i fix this? i see other people using it, and they get player info/ping, but it will not display for me at all. 

this has been a persistent problem for me in all releases of steamp2p info. i have been trying to get this program to work since you released it and have been hoping whatever is causing this issue would have been ironed out in future releases, but that does not appear to be the case. any ideas on what i can do to get this program to work as well for me as it seems to for other players?

**Comment by Githubaccountforrandomshit** [comment]
You have to enter command in Steam console

**Comment by cridus** [comment]
Please check if this file is being written into by Steam once you execute the command:  
`C:\Program Files (x86)\Steam\logs\ipc_SteamClient.log`

**Comment by Nickesponja** [comment]
Hi, I'm having the same problem, and indeed steam isn't writing anything in that file. Any idea why and how to fix it?

**Comment by cridus** [comment]
tremwil for sure knows better than me what might be going on, but in the meantime: check if the permissions on that file are as follows:
```
- all applications:                          read & execute, read
- all applications (with restrictions):      read & execute, read
- system:                                    full control
- administrators:                            full control
- users:                                     full control
```
  
that's how they are on my end (the names of the first 2 groups might be different as they're in italian on my pc).

**Comment by Nickesponja** [comment]
That's exactly how they are. It's also not read-only.

**Comment by AlexGutter** [comment]
Has anyone found a solution to this problem?

**Comment by tremwil** [comment]
Most likely cause was the same as #30, which should be fixed thanks to @zkxs's contributions. Closing, open a new issue if the bug you're experiencing still persists.
