### ISSUE TITLE
Console not working after latest steam update

### ISSUE THREAD

**Issue by Yes-Maidenless** [tremwil/SteamP2PInfo#32]
Hi and thanks for this app, it's great. After the last steam update p2p info no longer activates the console. It can be manually opened using steam://open/console so we still have access to it. Any suggestions on a fix or work-around? It's not a big issue and I can still do it manually, I'm just lazy and want u to do more work :) Thanks again!

**Comment by cridus** [comment]
It only happened once to me, the very first time. I think I simply closed and reopened the application and it worked correctly, then (and the subsequent times too, through multiple days).

**Comment by Yes-Maidenless** [comment]
hmm. I have to manually do it every time steam closes.

**Comment by Yes-Maidenless** [comment]
Mods u can close this thread. Something must have been up with my steam. After a windows restore to before the steam update, then update- It's been working every time (5)
