### ISSUE TITLE
HDR Display Issues with Overlay

### ISSUE THREAD

**Issue by Bioanalytica** [tremwil/SteamP2PInfo#37]
It's not possible to use SteamP2P with HDR enabled because the display becomes super bright and washed out, disabling HDR fixes problem.

**Comment by tremwil** [comment]
This is weird as the overlay window is a WPF window, which should have HDR support.  Sadly, I don't have an HDR display to test this so I'm afraid I won't be able to fix it unless someone has more detailed information.

**Comment by Bioanalytica** [comment]
I guess this was a bug with Elden Ring specifically because they mentioned they fixed an HDR issue in a recent patch and now it's working great with Fullscreen/HDR.
