### ISSUE TITLE
New version 1.10 

### ISSUE THREAD

**Issue by Yes-Maidenless** [tremwil/SteamP2PInfo#40]
I don't think this is working at all in the colosseum now. 1st 10 fights no connections shown. I've yet to see 1.10 work. I'll keep trying. Old version seemed more reliable. I would have maybe 6 out of 10 to show previously. edit: switched to old version got 9 out of 10 matches shown. Went back to 1.10 for 5 more tries still nothing.

**Comment by tremwil** [comment]
Hi, note that for this version the command you have to paste in the Steam console has changed. Did you do so after updating?

**Comment by Yes-Maidenless** [comment]
Yeah i don't remember it asking me for the command and steam hadn't been closed so it probably had the old command in use. After closing steam it's now working. Thanks.

**Comment by Yes-Maidenless** [comment]
I can say i've yet to get a blank display with the new version.. although when invading it sometimes only shows 1 person out of the group. Old version if it showed 1 person it showed them all. I'm not going to start a new issue as my previous issues have been local issues on my machine and not an issue with the app.

**Comment by Yes-Maidenless** [comment]
issue resolved
