### ISSUE TITLE
Error messages in steam console

### ISSUE THREAD

**Issue by Covfefe-45** [tremwil/SteamP2PInfo#43]
I'm getting a bunch of errors in steam console with the new version. I'm assuming it's errors, it's in red. Not sure if its actually causing issues, I haven't noticed anything. Says  "Stop spewing for IClientUser::EndAuthSession, too many calls." I've attached steam log and a picture as the steam log doesn't seem to show everything i see in the console.

![Screenshot 2024-02-13 040424](https://github.com/tremwil/SteamP2PInfo/assets/137660197/cfb8254b-f074-4d78-81b6-cde9969f2bb6)
[ipc_SteamClient.log](https://github.com/tremwil/SteamP2PInfo/files/14258491/ipc_SteamClient.log)

**Comment by tremwil** [comment]
These error messages are expected. To fix Steam not flushing flushing the log file, the program now periodically improperly calls to a misc SteamFreinds function so log entries keep being printed. The `Stop spewing` warning isn't an issue either, as it only stops writing to the console, not the IPC log file.
