### ISSUE TITLE
blank box when opening SteamP2PInfo file

### ISSUE THREAD

**Issue by ZombieBossTheGreat** [tremwil/SteamP2PInfo#47]
idk how to fix this issue :(
![Screenshot 2024-04-20 165613](https://github.com/tremwil/SteamP2PInfo/assets/136408329/e5bcc6ec-6925-425d-8c33-9fb518cbafc5)

**Comment by cridus** [comment]
Are you actually trying to modify the source code or did you download the sources instead of the executable?
To download the compiled executable you need to go to [Releases](https://github.com/tremwil/SteamP2PInfo/releases).

**Comment by ZombieBossTheGreat** [comment]
> Are you actually trying to modify the source code or did you download the sources instead of the executable? To download the compiled executable you need to go to [Releases](https://github.com/tremwil/SteamP2PInfo/releases).

thank you I have never really used Github before
