### ISSUE TITLE
k_EAccountTypeClan

### ISSUE THREAD

**Issue by 1DirtyMonk1** [tremwil/SteamP2PInfo#48]
![Screenshot 2024-04-27 184038](https://github.com/tremwil/SteamP2PInfo/assets/168276007/1f82c297-1f75-44b9-9509-fca3ffc956f4)
Game - Elden Ring.
Works normally only with V1.0.6.

**Comment by tremwil** [comment]
These errors messages are expected. To force Steam to flush the IPC log file and make sure the app can get up-to-date information on peers, it periodically calls SendClanChatMessage with invalid arguments. This doesn't do anything except showing this error message and a line being written to the IPC log. 

FWIW, the reason why SendClanChatMessage was used for this purpose is that it's not something a game is likely to call often, so if we log these calls, then the original ones by the game won't spam the console too much.
