### ISSUE TITLE
Cool utility question

### ISSUE THREAD

**Issue by heryoff** [tremwil/SteamP2PInfo#5]
Hey I would like to know if there is anyway that this tool could have a “Disconnect” button type thing. 
I know it sounds kinda sketchy but I keep getting this AFK farmer and it would be much easier to press a quick button instead of going around the menus to disconnect from the session.

I used the DS3 tool which was super handful with the invasion keybind, but I know in ER it’s not possible due to this shit anticheat (shit because of the problem that comes with it)

**Comment by tremwil** [comment]
Hi! 

Despite the presence of EAC, It would still be possible to implement a form of "Leave Session" hotkey. However, it would work differently from the one available in my Dark Souls 3 program, as EAC prevents accessing the game process.

That being said, I am not planning to implement this at all for the two following reasons:

- The forceful disconnect would have to work by blocking the connection to the player directly. This may cause issues for both parties, such as sometimes having to wait for the game's 30 second connection timeout or even triggering the multiplayer disconnect penalty, which prevents you from playing online for 12 hours of in-game (character) time.

- I'ce received many reports of people abusing this feature in DS3 as it was essentially a faster alt f4 that didn't require you to restart your game.

For your specific situation, note that the player block system that existed in DS3 is still present in Elden Ring. If you click on the name of a player in the "Session Info" tab, their profile page will open in the Steam overlay. From there, you can simply block them and this will prevent you from ever seeing them in-game again. However, note that it may take up to 5 minutes for the game to sync your Steam blocklist.
