### ISSUE TITLE
unauthorized access exception

### ISSUE THREAD

**Issue by howie0913** [tremwil/SteamP2PInfo#51]
![image](https://github.com/tremwil/SteamP2PInfo/assets/64137270/0de72ea0-4c6f-4304-a2c7-16d6a93af336)
I followed the instuctions and also made sure that the path to the log files are correct, but the app keep saying that there's an unhandled  exception: unauthorized access exception.

**Comment by tremwil** [comment]
Hi, can you send a screenshot of the full stack trace of the error? Or use the "copy stack trace" button (not sure it's called that exactly, the one that shows up when the app crashes).

**Comment by howie0913** [comment]
sure, it says:
 UnauthorizedAccessException: Deny access path 'D:\steam\logs'。
   At System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   At System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   At System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   At SteamP2PInfo.SteamPeerManager.<UpdatePeerList>d__14.MoveNext()
--- End of stack trace in position where exception was previously thrown ---
   At System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   At System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   At System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by tremwil** [comment]
It seems like you've entered the path to the IPC log folder instead of the actual file. Try to set the IPC log file path to the following:

`D:\steam\logs\ipc_SteamClient.log`

**Comment by howie0913** [comment]
hey it actually worked, thx a lot.
