### ISSUE TITLE
Tekken 7

### ISSUE THREAD

**Issue by Hinkiii** [tremwil/SteamP2PInfo#7]
For some reason it doesn't pick up any of the ipc info it could be cause the log gets flooded with tekken specific vars

**Comment by Hinkiii** [comment]
Sorry just had to edit SteamPeerManager.cs I thought that attaching another process was enough lol

**Comment by tremwil** [comment]
It should be enough. What bug(s) did you encounter that prevented the tool from working with Tekken? Since I'm trying to support all games, I'll fix it.

**Comment by Hinkiii** [comment]
Just didn't show the SteamID at all until I built with that change I even used the same config file from when I was trying it idk it could just be a fluke though cause sometimes I know it didn't pick up specific people in Elden Ring
Like someone I play with never showed up but another would

**Comment by Hinkiii** [comment]
Was just line 87 I assume it's redundant but at least with the small batch I was working with it started to actually show the steam p2p session

` if (!line.Contains("TekkenGame-Win64-Shipping.exe") || line.Contains("IClientMatchmaking::LeaveLobby"))`

**Comment by tremwil** [comment]
No you're definitely right, this was dumb typo on my part. Should definitely have tested with other games myself!
